#!/bin/bash
echo "SAR Ship Detection Pipeline - Docker Container"
echo "============================================="
echo "Available commands:"
echo "  python demo.py                    - Run the full demo"
echo "  python denoise_hrsid_val.py       - Run denoising on HRSID dataset"
echo "  python detect.py                   - Run detection on images"
echo "  python detect.py --source test_ingest/ --weights runs/train/experiment3/weights/best.pt --device 0  - Test detection with GPU"
echo "  python train.py                    - Train a model"
echo "  python val.py                      - Validate a model"
echo "  bash                               - Get a shell"
echo ""
echo "To run the demo, use: python demo.py"
echo "To test detection directly, use: python detect.py --source test_ingest/ --weights runs/train/experiment3/weights/best.pt --device 0"
echo "To get a shell, use: bash"
echo ""
exec "$@" 